apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: fah-placement
  namespace: fahclient
  labels:
    app: fahclient-centos8
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchLabels: 
      vendor: OpenShift
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
